# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e002bc5f8a4b73c93d6dd4c5019b3c42cb5894441eb7549768a467b64046b9e9031ae08f95340affdf7a57ec32180fc16fd30acd55fe3ce879f50874854aab50

test:
  secret_key_base: 54350eaafed1bcfb136d34bd38bc4d78e1a67188e35d862f0de0beacf8c54f86ec687a72fdefced4eb5a7d54c0a72bb8dc8bf1cdb02433900b4f3d86c27ccea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
